services:
  opensettings:
    image: OpenSettings/open-settings:latest
    container_name: container-open-settings
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OPENSETTINGS_Configuration__DbProviderName=InMemory
      - OPENSETTINGS_Configuration__ConnectionString=OpenSettings
    ports:
      - "5388:8080"