version: '3.8'

services:
  opensettings:
    image: OpenSettings/open-settings:latest
    container_name: container-open-settings
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5388:5000"